---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels: 
    app: demo
    run: demo
  annotations:
    argocd.argoproj.io/sync-options: '{"automated": true}'
spec:
  containers:
    - image: gcr.io/k8s-k3s/demo:v1.0.0
      name: app
      ports:
        - containerPort: 8000
          name: http
